import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { useRef, useEffect } from "react";
import { getPositions } from "../components/singleComponents/Utils/Utils";
import Hero from "../components/Home/Hero";
import SoulAether from "../components/Home/SoulAether";
import KiwiKickz from "../components/Home/KiwiKickz";

const Home: NextPage = () => {
  const fwdRef = useRef<HTMLHeadingElement>(null);
  return (
    <div className={styles.container}>
      <Head>
        <title>Nikolai Sim Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/psyFav.gif" />
      </Head>

      <main className={styles.main}>
        <Hero />
        <SoulAether />
        <KiwiKickz />
        <KiwiKickz />
        <KiwiKickz />
      </main>
    </div>
  );
};

export default Home;
